#!/usr/bin/env node
/**
 * fv_schema_gate.js — every field in MAPS must have a real column in Postgres.
 *
 * Two production incidents came from this gap being guarded by human memory:
 * movements.photos was mapped but never created (every movement upsert failed
 * silently for ~14 h, 2026-08-01, rows permanently lost), and status_events
 * shipped without show_id. This gate makes the rule mechanical: preflight
 * refuses to clear a build whose MAPS names a column Postgres doesn't have.
 *
 * HOW IT GETS THE REAL SCHEMA WITHOUT CREDENTIALS
 * -----------------------------------------------
 * `GET /rest/v1/<table>?select=<cols>&limit=0` with the public anon key
 * returns 200 when every column exists and Postgres 42703 NAMING the missing
 * column when one doesn't — RLS hides rows, not column errors. (The OpenAPI
 * endpoint is a dead end: empty definitions for the anon role.)
 *
 * MODES — the gate never silently skips:
 *   live     network up:   probe every table, then rewrite schema.snapshot.json
 *            (the snapshot is machine-generated; never edit it by hand)
 *   snapshot network down: verify mapped ⊆ committed snapshot, loud banner
 *   neither  no network and no snapshot -> exit 1 (refuses to vouch blind)
 *
 * Checked per table: every value of MAPS[t].m PLUS MAPS[t].ro — read-only
 * columns are the same drift class (received_at was mapped on three tables it
 * didn't exist on, found 2026-08-01).
 *
 * Usage:
 *   node tools/fv_schema_gate.js              (gate; run by preflight)
 *   node tools/fv_schema_gate.js --selftest   (proves 42703 detection live)
 * Zero npm dependencies. FV_URL / FV_ANON_KEY override the defaults.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { load } = require('./fv_harness.js');

const URLB = process.env.FV_URL || 'https://eujgglfcpdfgskyqfggg.supabase.co';
const ANON = process.env.FV_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1amdnbGZjcGRmZ3NreXFmZ2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1ODI4MDksImV4cCI6MjEwMDE1ODgwOX0.0OCf7DeBOeaU3WgihQ2E-cSQ7WdUFPy7DsQJ_2X_8xc';
const SNAPSHOT = path.join(__dirname, 'schema.snapshot.json');

/* MAPS is the single source of truth for what the client writes; pull it from
 * the real app so the gate can never drift from the code it guards. */
function mappedColumns() {
  const app = load(path.join(__dirname, '..', 'index.html'), { tolerateEvalError: true });
  const MAPS = app.live.MAPS;
  if (!MAPS || !Object.keys(MAPS).length) throw new Error('could not extract MAPS from index.html');
  const out = {};
  for (const [table, def] of Object.entries(MAPS)) {
    out[table] = [...new Set([...Object.values(def.m || {}), ...(def.ro || [])])].sort();
  }
  return out;
}

/* One probe per table. Returns null on pass, an error string on 42703, and
 * THROWS on network trouble (so the caller can fall back to the snapshot). */
async function probeTable(table, cols) {
  const url = `${URLB}/rest/v1/${table}?select=${cols.join(',')}&limit=0`;
  const res = await fetch(url, { headers: { apikey: ANON }, signal: AbortSignal.timeout(15000) });
  if (res.status === 200 || res.status === 206) return null;
  const body = await res.json().catch(() => ({}));
  if (body && body.code === '42703') return `${table}: ${body.message}`;
  // 404 = table itself missing; anything else is a real schema-side failure too
  if (res.status === 404) return `${table}: table does not exist (HTTP 404)`;
  throw new Error(`${table}: HTTP ${res.status} ${JSON.stringify(body).slice(0, 120)}`);
}

async function runLive(mapped) {
  const failures = [];
  for (const [table, cols] of Object.entries(mapped)) {
    const f = await probeTable(table, cols);
    if (f) failures.push(f);
  }
  return failures;
}

function checkSnapshot(mapped) {
  if (!fs.existsSync(SNAPSHOT)) return { failures: null, date: null };
  const snap = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
  const failures = [];
  for (const [table, cols] of Object.entries(mapped)) {
    const have = new Set(snap.tables[table] || []);
    if (!snap.tables[table]) { failures.push(`${table}: table not in snapshot`); continue; }
    for (const c of cols) if (!have.has(c)) failures.push(`${table}.${c} not in snapshot`);
  }
  return { failures, date: snap.verified_at };
}

function writeSnapshot(mapped) {
  /* The snapshot records what the LIVE probe just verified — mapped columns
   * that Postgres accepted. Machine-generated on every successful live gate. */
  const next = { verified_at: new Date().toISOString(),
    note: 'machine-generated by fv_schema_gate.js on a successful live probe — do not edit by hand',
    tables: mapped };
  const prev = fs.existsSync(SNAPSHOT) ? fs.readFileSync(SNAPSHOT, 'utf8') : '';
  const prevTables = prev && JSON.stringify(JSON.parse(prev).tables);
  if (prevTables === JSON.stringify(next.tables)) return false;   // unchanged -> keep old date, no churn
  const tmp = SNAPSHOT + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(next, null, 2));
  fs.renameSync(tmp, SNAPSHOT);
  return true;
}

async function gate() {
  const mapped = mappedColumns();
  const nCols = Object.values(mapped).reduce((n, c) => n + c.length, 0);
  try {
    const failures = await runLive(mapped);
    if (failures.length) {
      console.error('SCHEMA GATE FAILED — mapped field(s) with no Postgres column:');
      failures.forEach((f) => console.error('  ' + f));
      console.error('Run the migration (one idempotent batch, dashboard SQL editor) BEFORE deploying this client.');
      return 1;
    }
    const rewrote = writeSnapshot(mapped);
    console.log(`schema gate: LIVE — ${Object.keys(mapped).length} tables, ${nCols} mapped columns all exist` +
      (rewrote ? ' (snapshot refreshed — commit it)' : ''));
    return 0;
  } catch (e) {
    const { failures, date } = checkSnapshot(mapped);
    if (failures === null) {
      console.error(`SCHEMA GATE FAILED — no network (${e.message}) and no ${path.basename(SNAPSHOT)} to fall back to.`);
      console.error('The gate refuses to vouch blind. Get network once, or commit a snapshot from a machine that has it.');
      return 1;
    }
    if (failures.length) {
      console.error(`SCHEMA GATE FAILED (offline, snapshot dated ${date}):`);
      failures.forEach((f) => console.error('  ' + f));
      return 1;
    }
    console.log(`schema gate: [OFFLINE — verified against snapshot dated ${date}] ` +
      `${Object.keys(mapped).length} tables, ${nCols} mapped columns. Live probe failed: ${e.message}`);
    return 0;
  }
}

/* --selftest: the detection path must stay provably alive — probe a column
 * that must never exist and demand the named 42703. A gate that only ever
 * sees passing schemas is a gate nobody has watched fail. */
async function selftest() {
  let code = 0;
  const t = (name, cond) => { if (!cond) { console.error('FAIL: ' + name); code = 1; } };

  const mapped = mappedColumns();
  t('MAPS extraction finds the seven tables', Object.keys(mapped).length === 7);
  t('shows maps show_days', mapped.shows.includes('show_days'));
  t('reports maps received_at via ro', mapped.reports.includes('received_at'));

  try {
    const fake = await probeTable('shows', ['id', 'column_that_must_never_exist']);
    t('fake column -> named 42703', !!fake && fake.includes('column_that_must_never_exist'));
    const real = await probeTable('shows', mapped.shows);
    t('real columns -> pass', real === null);
  } catch (e) {
    console.log('selftest: network unavailable (' + e.message + ') — live-detection checks skipped, offline path tested instead');
  }

  // offline fallback logic against a fixture (pure, no I/O beyond reading nothing)
  const snapFixture = { tables: { shows: ['id', 'name'] } };
  const have = new Set(snapFixture.tables.shows);
  t('snapshot subset check catches a missing column', !have.has('show_days'));

  console.log(code ? 'SELFTEST FAILED' : 'selftest OK');
  return code;
}

(async () => {
  const code = process.argv.includes('--selftest') ? await selftest() : await gate();
  process.exit(code);
})().catch((e) => { console.error('FATAL:', e.message || e); process.exit(1); });
