#!/usr/bin/env node
/**
 * fv_smoke.js — FleetView standing regression suite.
 *
 * These are the INVARIANTS. They encode the product contracts the crew's night
 * depends on — the arm's-length status colors, the sacred per-job/asset-level
 * separation, service math, scan dedup, and data-layer round-tripping.
 * If one of these fails, DO NOT DEPLOY.
 *
 * Per-deploy you do NOT edit this file. You write a small assertions file for
 * the new feature and pass it as an extra:
 *
 *   node fv_smoke.js index.html                  # invariants only
 *   node fv_smoke.js index.html feat_assert.js   # invariants + new feature
 *
 * An extras file exports a function: module.exports = (app, t) => { ... }
 * where `app` is the loaded harness and `t` is the assertion helper.
 *
 * Exit code 0 = safe to deploy. Non-zero = blocked.
 */
'use strict';

const path = require('path');
const { load } = require('./fv_harness.js');
const { makeT, report } = require('./fv_assert.js');

const args = process.argv.slice(2);
const htmlPath = args[0] && !args[0].endsWith('.js') ? args[0] : 'index.html';
const extras = args.filter((a) => a.endsWith('.js'));

/* ---------------- fixture builders ---------------- */
const HOUR = 3600e3;
let seq = 0;
const id = (p) => `${p}-${++seq}`;

const mkUnit = (o = {}) =>
  Object.assign(
    {
      id: id('u'),
      tagId: id('TAG'),
      serial: id('SER'),
      make: 'MQ',
      model: 'TW-300',
      kw: 300,
      currentHours: 100,
      serviceDueHours: 500,
      opStatus: 'running',
      klass: 'big',
      locationType: 'show',
      locationId: 'show-A',
      photos: [],
      jobMeta: {},
    },
    o
  );

const mkReport = (unitId, o = {}) =>
  Object.assign({ id: id('r'), unitId, showId: 'show-A', techName: 'Mike R.', timestamp: Date.now() - HOUR }, o);

const mkIssue = (unitId, o = {}) =>
  Object.assign(
    { id: id('i'), unitId, showId: 'show-A', severity: 'cosmetic', title: 'Scratched panel', techName: 'Mike R.', timestamp: Date.now() - HOUR, resolved: false, photos: [] },
    o
  );

/* ---------------- run ---------------- */
let app;
const t = makeT();

t.group('boot');
try {
  app = load(htmlPath);
  t.ok(true, 'index.html parses and evaluates with no uncaught error');
} catch (e) {
  t.ok(false, 'index.html parses and evaluates', e.message);
  report(t, `FleetView smoke — ${path.basename(htmlPath)}`);
  process.exit(1);
}
t.eq(app.consoleErrors.length, 0, 'no console.error during boot' + (app.consoleErrors[0] ? ` (${app.consoleErrors[0]})` : ''));
t.ok(app.fnNames.length > 100, `app surface intact (${app.fnNames.length} functions)`);
t.ok(!!app.S && !!app.S.settings, 'state object S initialises with settings');
[
  'computeStatus', 'serviceState', 'isStale', 'assetLabel', 'jm', 'placeOf',
  'byKva', 'toRow', 'fromRow', 'unitByCode', 'jobHealth', 'latestFuel',
  'openIssuesFor', 'needsAttention', 'esc', 'blankState',
].forEach((n) => t.ok(typeof app.fn[n] === 'function', `core function present: ${n}`));

/* ============================================================
 * STATUS COLOR CONTRACT — the arm's-length signal.
 * Precedence: down(red) > overService > maintenance > lowFuel >
 *             serviceSoon (all orange) > cosmetic(yellow) >
 *             transit(blue) > running(green) > staged(grey)
 * ============================================================ */
t.group('status colors (arm\'s length)');
{
  const S = app.setState({ settings: Object.assign(app.fn.blankState().settings, { warnHours: 20, staleHours: 6 }) });

  const check = (label, unit, extras2 = {}) => {
    S.units = [unit];
    S.reports = extras2.reports || [];
    S.issues = extras2.issues || [];
    return app.fn.computeStatus(unit);
  };

  t.eq(check('running', mkUnit()).color, 'green', 'healthy running unit is GREEN');
  t.eq(check('staged', mkUnit({ opStatus: 'staged' })).color, 'grey', 'staged unit is GREY');
  t.eq(check('transit', mkUnit({ opStatus: 'staged', locationType: 'transit' })).color, 'blue', 'in-transit unit is BLUE');

  const u1 = mkUnit({ opStatus: 'down' });
  t.eq(check('down', u1).color, 'red', 'opStatus down is RED');

  const u2 = mkUnit();
  t.eq(check('down issue', u2, { issues: [mkIssue(u2.id, { severity: 'down' })] }).color, 'red',
    'open DOWN issue forces RED even when opStatus says running');

  const u3 = mkUnit();
  t.eq(check('cosmetic', u3, { issues: [mkIssue(u3.id, { severity: 'cosmetic' })] }).color, 'yellow',
    'open cosmetic issue is YELLOW');

  const u4 = mkUnit();
  t.eq(check('maint', u4, { issues: [mkIssue(u4.id, { severity: 'maintenance' })] }).color, 'orange',
    'open maintenance issue is ORANGE');

  t.eq(check('over svc', mkUnit({ currentHours: 520, serviceDueHours: 500 })).color, 'orange',
    'past service hours is ORANGE');
  t.eq(check('svc soon', mkUnit({ currentHours: 490, serviceDueHours: 500 })).color, 'orange',
    'within warnHours of service is ORANGE');

  const u5 = mkUnit();
  t.eq(check('low fuel', u5, { reports: [mkReport(u5.id, { fuelLevelPct: 12 })] }).color, 'orange',
    'fuel under 20% is ORANGE');

  // precedence: down must win over everything
  const u6 = mkUnit({ opStatus: 'down', currentHours: 520, serviceDueHours: 500 });
  t.eq(check('down+over', u6, { reports: [mkReport(u6.id, { fuelLevelPct: 5 })] }).color, 'red',
    'DOWN outranks over-service and low fuel');

  // resolved issues must not colour the unit
  const u7 = mkUnit();
  t.eq(check('resolved', u7, { issues: [mkIssue(u7.id, { severity: 'down', resolved: true })] }).color, 'green',
    'resolved issues do not affect status');
}

/* ============================================================
 * SERVICE MATH — boundaries
 * ============================================================ */
t.group('service math');
{
  const S = app.setState({});
  S.settings.warnHours = 20;
  const sv = (cur, due) => app.fn.serviceState(mkUnit({ currentHours: cur, serviceDueHours: due }));

  t.eq(sv(500, 500).state, 'over', 'exactly at due hours counts as OVER');
  t.eq(sv(501, 500).state, 'over', 'past due is OVER');
  t.eq(sv(480, 500).state, 'soon', 'exactly warnHours out is SOON');
  t.eq(sv(479, 500).state, 'ok', 'just beyond warnHours is OK');
  t.eq(sv(100, 500).state, 'ok', 'plenty of runway is OK');
  t.eq(app.fn.serviceState(mkUnit({ serviceDueHours: null })).state, 'unknown', 'missing due hours is UNKNOWN');
  t.eq(app.fn.serviceState(mkUnit({ currentHours: null })).state, 'unknown', 'missing current hours is UNKNOWN');
  t.eq(sv(495, 500).remaining, 5, 'remaining hours computed correctly');
}

/* ============================================================
 * FRESHNESS — how old is the last check
 * ============================================================ */
t.group('freshness / staleness');
{
  const S = app.setState({});
  S.settings.staleHours = 6;
  const u = mkUnit();
  S.units = [u];

  S.reports = [];
  t.ok(app.fn.isStale(u), 'a unit that has never been checked is STALE');

  S.reports = [mkReport(u.id, { timestamp: Date.now() - 1 * HOUR })];
  t.ok(!app.fn.isStale(u), 'checked 1h ago is fresh');

  S.reports = [mkReport(u.id, { timestamp: Date.now() - 9 * HOUR })];
  t.ok(app.fn.isStale(u), 'checked 9h ago is stale at staleHours=6');

  const d = mkUnit({ opStatus: 'down' });
  S.units = [d];
  S.reports = [];
  t.ok(!app.fn.isStale(d), 'a DOWN unit is never reported stale (it is already red)');
}

/* ============================================================
 * PER-JOB vs ASSET-LEVEL — this separation is sacred.
 * A per-job name/placement must NEVER follow the asset to the next show.
 * ============================================================ */
t.group('per-job isolation (SACRED)');
{
  const S = app.setState({});
  const JOB_A = 'show-A', JOB_B = 'show-B';
  const u = mkUnit({
    kw: 150,
    area: undefined,
    jobMeta: { [JOB_A]: { name: 'Coca-Cola AC', area: 'VIP Tent', note: 'behind the bar' } },
  });
  S.units = [u];

  t.eq(app.fn.assetLabel(u, JOB_A), 'Coca-Cola AC', 'per-job name shows on the job that set it');
  t.excludes(app.fn.assetLabel(u, JOB_B), 'Coca-Cola AC', 'per-job name must NOT leak to another job');
  t.includes(app.fn.assetLabel(u, JOB_B), '150 kVA', 'other job falls back to asset spec label');

  t.eq(app.fn.placeOf(u, JOB_A), 'VIP Tent', 'per-job placement shows on its own job');
  t.excludes(app.fn.placeOf(u, JOB_B), 'VIP Tent', 'per-job placement must NOT leak to another job');

  t.deep(app.fn.jm(u, JOB_B), {}, 'jobMeta lookup for an unknown job is empty, not inherited');
  t.deep(app.fn.jm(u, null), {}, 'jobMeta lookup with no job id is empty');

  // Asset-level facts DO travel with the unit, forever.
  t.eq(u.serial, app.fn.unitById ? u.serial : u.serial, 'asset serial is asset-level');
  const spec = app.fn.assetLabel(mkUnit({ kw: 500, jobMeta: {} }), JOB_B);
  t.includes(spec, '500 kVA', 'asset specs travel with the asset');
}

/* ============================================================
 * SCAN / DEDUP — the license-plate model.
 * Scan an existing tag; unknown code prompts add-once; linked forever.
 * ============================================================ */
t.group('scan dedup (license plate)');
{
  const S = app.setState({});
  const u = mkUnit({ serial: '28B10199', tagId: 'CES-4471' });
  S.units = [u];

  t.eq(app.fn.unitByCode('28B10199'), u, 'scan matches on serial');
  t.eq(app.fn.unitByCode('CES-4471'), u, 'scan matches on asset tag id');
  t.eq(app.fn.unitByCode('28b10199'), u, 'scan is case-insensitive');
  t.eq(app.fn.unitByCode('  28B10199  '), u, 'scan tolerates surrounding whitespace');
  t.eq(app.fn.unitByCode('NOPE-9999'), null, 'unknown code returns null so the add-once flow can fire');
  t.eq(app.fn.unitByCode(''), null, 'empty code returns null');
  t.eq(app.fn.unitByCode(null), null, 'null code returns null and does not throw');
}

/* ============================================================
 * DATA LAYER — snake_case round-trip must not lose or corrupt data
 * ============================================================ */
t.group('data layer round-trip');
{
  app.setState({});
  const ts = 1750000000000;
  const unit = mkUnit({
    tagId: 'CES-1',
    serial: 'S-1',
    kw: 300,
    jobMeta: { 'show-A': { name: 'Coca-Cola AC' } },
    createdAt: ts,
    updatedAt: ts,
  });

  const row = app.fn.toRow('units', unit);
  t.eq(row.tag_id, 'CES-1', 'camelCase tagId maps to snake_case tag_id');
  t.eq(row.job_meta['show-A'].name, 'Coca-Cola AC', 'jobMeta maps to job_meta and survives');
  t.eq(typeof row.created_at, 'string', 'timestamps serialise to ISO strings for Postgres');
  t.ok(!('tagId' in row), 'no camelCase keys leak into the DB row');

  const back = app.fn.fromRow('units', row);
  t.eq(back.tagId, 'CES-1', 'round-trip restores tagId');
  t.eq(back.createdAt, ts, 'round-trip restores millisecond timestamp exactly');
  t.eq(back.jobMeta['show-A'].name, 'Coca-Cola AC', 'round-trip preserves per-job metadata');
  t.eq(back.kw, 300, 'round-trip preserves numeric specs');

  const rep = mkReport('u-x', { timestamp: ts, fuelLevelPct: 55, coolantTemp: 184 });
  const rrow = app.fn.toRow('reports', rep);
  t.eq(rrow.ts, new Date(ts).toISOString(), 'report timestamp maps to ts as ISO');
  t.eq(rrow.fuel_level_pct, 55, 'report vitals map to snake_case');
  t.eq(app.fn.fromRow('reports', rrow).timestamp, ts, 'report timestamp round-trips exactly');
}

/* ============================================================
 * EVERY FIELD IS OPTIONAL — never force a photo, never force a vital
 * ============================================================ */
t.group('optional fields (no forced photos)');
{
  const S = app.setState({});
  const u = mkUnit();
  S.units = [u];
  // A routine check with nothing but a timestamp and a name must be valid.
  const bare = { id: 'r-bare', unitId: u.id, showId: 'show-A', techName: 'Mike R.', timestamp: Date.now() };
  S.reports = [bare];
  t.noThrow(() => app.fn.computeStatus(u), 'status computes from a report with no vitals at all');
  t.eq(app.fn.latestFuel(u), null, 'missing fuel reading reads as null, not 0');
  t.noThrow(() => app.fn.toRow('reports', bare), 'a bare report serialises without throwing');
  t.eq(app.fn.toRow('reports', bare).coolant_temp, null, 'unset vitals persist as null');

  const noPhoto = mkIssue(u.id, { photos: [] });
  S.issues = [noPhoto];
  t.noThrow(() => app.fn.computeStatus(u), 'an issue with no photos is still a valid issue');

  t.noThrow(() => app.fn.toRow('units', mkUnit({ kw: null, serial: null, tagId: null })), 'a barely-filled unit serialises');
}

/* ============================================================
 * FUEL + SORT + HEALTH
 * ============================================================ */
t.group('fuel, sort order, job health');
{
  const S = app.setState({});
  const u = mkUnit();
  S.units = [u];
  S.reports = [
    mkReport(u.id, { timestamp: Date.now() - 5 * HOUR, fuelLevelPct: 80 }),
    mkReport(u.id, { timestamp: Date.now() - 1 * HOUR, fuelLevelPct: 35 }),
    mkReport(u.id, { timestamp: Date.now() - 2 * HOUR, fuelLevelPct: 60 }),
  ];
  t.eq(app.fn.latestFuel(u), 35, 'latest fuel reading wins regardless of insert order');

  // sort: non-down before down, then ascending kVA, null kVA last
  const small = mkUnit({ kw: 60, serial: 'A' });
  const big = mkUnit({ kw: 500, serial: 'B' });
  const nokw = mkUnit({ kw: null, serial: 'C' });
  const down = mkUnit({ kw: 100, serial: 'D', opStatus: 'down' });
  S.units = [down, nokw, big, small];
  S.reports = [];
  S.issues = [];
  const sorted = app.fn.sortUnits(S.units.slice()).map((x) => x.serial);
  t.eq(sorted[0], 'A', 'smallest running unit sorts first');
  t.eq(sorted[1], 'B', 'then larger running units by kVA');
  t.eq(sorted[2], 'C', 'units with no kVA sort after known sizes');
  t.eq(sorted[3], 'D', 'DOWN units sort to the end of the list');

  // job health counts
  const shw = { id: 'show-A', name: 'Desert Sound', startDate: new Date().toISOString().slice(0, 10) };
  S.shows = [shw];
  S.settings.staleHours = 6;
  const good = mkUnit({ locationId: 'show-A' });
  const bad = mkUnit({ locationId: 'show-A', opStatus: 'down' });
  S.units = [good, bad];
  S.reports = [mkReport(good.id, { timestamp: Date.now() - 1 * HOUR }), mkReport(bad.id, { timestamp: Date.now() - 1 * HOUR })];
  const h = app.fn.jobHealth(shw);
  t.eq(h.units, 2, 'job health counts units on the job');
  t.eq(h.down, 1, 'job health counts down units');
  t.eq(h.overdue, 0, 'freshly checked units are not overdue');
}

/* Async sections + extras. saveName() awaits sb.auth.updateUser before it
 * stamps the name, so these assertions must await too. */
(async () => {
  /* ============================================================
   * PEOPLE, NOT EMAILS — logs stamped "Mike R."
   * ============================================================ */
  t.group('people not emails');
  {
    app.setState({});
    const stamp = async (first, last) => {
      app.document.querySelector('#pn_first').value = first;
      app.document.querySelector('#pn_last').value = last;
      try { await app.fn.saveName(); } catch (e) { /* render path is stubbed */ }
      return app.S.settings.techName;
    };
    t.eq(await stamp('Mike', 'Rodriguez'), 'Mike R.', 'name stamps as first name + last initial');
    t.eq(await stamp('Dana', ''), 'Dana', 'a first name alone is accepted');
    t.eq(await stamp('mike', 'rodriguez'), 'mike R.', 'last initial is upper-cased');
    t.excludes(String(app.S.settings.techName), '@', 'the stamp never contains an email address');

    // A blank first name must be rejected, not silently stamped.
    app.S.settings.techName = 'Mike R.';
    app.document.querySelector('#pn_first').value = '   ';
    try { await app.fn.saveName(); } catch (e) {}
    t.eq(app.S.settings.techName, 'Mike R.', 'a blank first name does not overwrite an existing stamp');
  }

  /* ============================================================
   * ESCAPING — field notes go into innerHTML
   * ============================================================ */
  t.group('escaping');
  {
    app.setState({});
    const out = app.fn.esc('<img src=x onerror="alert(1)"> & \'quotes\'');
    t.excludes(out, '<img', 'raw tags are escaped out of user text');
    t.excludes(out, 'onerror="', 'inline handlers cannot survive escaping');
    t.includes(out, '&lt;', 'angle brackets become entities');
    t.includes(out, '&amp;', 'ampersands become entities');
    t.eq(app.fn.esc(null), '', 'null text escapes to empty string');
    t.eq(app.fn.esc(0), '0', 'zero is preserved, not treated as empty');
  }

  /* ---------------- extra per-deploy assertions ---------------- */
  for (const f of extras) {
    const p = path.resolve(f);
    t.group('new: ' + path.basename(f, '.js'));
    try {
      const mod = require(p);
      if (typeof mod !== 'function') {
        t.ok(false, `${path.basename(f)} must export a function (app, t) => {...}`);
      } else {
        await mod(app, t);
      }
    } catch (e) {
      t.ok(false, `${path.basename(f)} ran without throwing`, e.message + '\n' + (e.stack || '').split('\n')[1]);
    }
  }

  /* ---------------- verdict ---------------- */
  const passed = report(
    t,
    `FleetView smoke — ${path.basename(htmlPath)}${extras.length ? ' + ' + extras.map((e) => path.basename(e)).join(', ') : ''}`
  );
  process.exit(passed ? 0 : 1);
})();
