-- ============================================================
-- NES IMPORT  --  generated from the approved match table
-- Idempotent. Re-running is a no-op. Nothing is deleted.
--   17 matched units updated (gaps only)
--   134 new units inserted
--   1 NES row held out: UVC700618 (transposed pair, see match table 2a)
-- Never written: hours, vitals, engines.style, job assignment, job_meta, photos.
-- ============================================================
begin;

-- ---------- 1. MATCHED: classification (NES is authoritative) ----------
update units set klass='big', updated_at=now() where serial='TGD62507' and klass<>'big';
update units set klass='big', updated_at=now() where serial='UVC700617' and klass<>'big';
update units set klass='big', updated_at=now() where serial='X5M00207' and klass<>'big';

-- ---------- 2. MATCHED: fill blank package rating ----------
update units set kw=750, updated_at=now() where serial='C5E02984-85' and kw is null;

-- ---------- 3. MATCHED: fill blank make (never overwrite) ----------
update units set make='CAT', updated_at=now() where serial='C5E02269/70' and coalesce(make,'')='';
update units set make='Atlas Copco', updated_at=now() where serial='UVC700616' and coalesce(make,'')='';
update units set make='Atlas Copco', updated_at=now() where serial='UVC700617' and coalesce(make,'')='';
update units set make='Atlas Copco', updated_at=now() where serial='UVC700619' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00207' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00213' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00296' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00306' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00357' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00388' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00394' and coalesce(make,'')='';
update units set make='CAT', updated_at=now() where serial='X5M00446' and coalesce(make,'')='';

-- ---------- 4. MATCHED: create engines where the NES says Twin ----------
-- Only where engines is null. style is deliberately ABSENT: the housing label is
-- physical, unset until a tech reads it, and renders as Engine 1 / Engine 2.
update units set engines='{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, updated_at=now() where serial='C5E02984-85' and engines is null;
update units set engines='{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, updated_at=now() where serial='TGD62501' and engines is null;
update units set engines='{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, updated_at=now() where serial='TGD62504' and engines is null;
update units set engines='{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, updated_at=now() where serial='TGD62507' and engines is null;
-- Config trap: these say config=TwinPak but the NES calls them SINGLES.
-- No engines statement is emitted for them, by design:
--   X5M00306  config=TwinPak  NES=500 kW
--   X5M00388  config=TwinPak  NES=500 kW
--   X5M00446  config=TwinPak  NES=500 kW

-- ---------- 5. MATCHED: append NES notes, marked, never overwriting ----------
update units set notes=case when coalesce(notes,'')='' then '[NES] No CA CARB' else notes||chr(10)||'[NES] No CA CARB' end, updated_at=now() where serial='1LS01712/14' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] 20''' else notes||chr(10)||'[NES] 20''' end, updated_at=now() where serial='C5E02269/70' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] 20''' else notes||chr(10)||'[NES] 20''' end, updated_at=now() where serial='C5E02984-85' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] 150 kW Loadbank' else notes||chr(10)||'[NES] 150 kW Loadbank' end, updated_at=now() where serial='TGD62501' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] NO Loadbank' else notes||chr(10)||'[NES] NO Loadbank' end, updated_at=now() where serial='TGD62504' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] 100kW Loadbank' else notes||chr(10)||'[NES] 100kW Loadbank' end, updated_at=now() where serial='TGD62507' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] ATLAS CopCo #2' else notes||chr(10)||'[NES] ATLAS CopCo #2' end, updated_at=now() where serial='UVC700616' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] ATLAS CopCo #2' else notes||chr(10)||'[NES] ATLAS CopCo #2' end, updated_at=now() where serial='UVC700617' and coalesce(notes,'') not like '%[NES]%';
update units set notes=case when coalesce(notes,'')='' then '[NES] ATLAS CopCo #4' else notes||chr(10)||'[NES] ATLAS CopCo #4' end, updated_at=now() where serial='UVC700619' and coalesce(notes,'') not like '%[NES]%';

-- ---------- 6. INSERT new units ----------
-- Unassigned, blank hours, no vitals, no label style. Hard-down from the NES is a
-- known office fact; everything else lands staged.
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), '17013144', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] Prod Power 500-1; Step Deck; 480 ONLY SINGLE UNIT DOES NOT PARALLEL' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='17013144');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), '17013580', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] Prod Power 500-2; Step Deck; 480 ONLY SINGLE UNIT DOES NOT PARALLEL' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='17013580');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), '17013584', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] Prod Power 500-3; Step Deck; 480 ONLY SINGLE UNIT DOES NOT PARALLEL' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='17013584');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), '17013722', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] Prod Power 500-4; Step Deck; 480 ONLY SINGLE UNIT DOES NOT PARALLEL' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='17013722');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS00652-653', 'big', 875, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 437.5}, "B": {"kvaEach": 437.5}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS00652653');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS00683-81', 'big', 1000, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0068381');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS00722-23', 'big', 875, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 437.5}, "B": {"kvaEach": 437.5}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0072223');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS00724-28', 'big', 875, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 437.5}, "B": {"kvaEach": 437.5}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0072428');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS01189-91', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0118991');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS01332/33', 'big', 750, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0133233');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS01390/91', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0139091');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS01478/79', 'big', 750, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0147879');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS01713-16', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0171316');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '1LS01715-17', 'big', 1000, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] Lift Gate' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0171517');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines) select gen_random_uuid(), '1LS01718-21', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='1LS0171821');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '396970/396971', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] DC; 208 V only' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='396970396971');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), '400-1', 'big', 500, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] Prod Power; TecnoGen S/N 18.55089; does Parallel' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='4001');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), '400-2', 'big', 500, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] Prod Power; does parallel' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='4002');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '4ZR01594-1601', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='4ZR015941601');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '4ZR02831-34', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='4ZR0283134');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), '4ZR03042-43', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 30''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='4ZR0304243');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, notes) select gen_random_uuid(), 'A190484324', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Cummins', '[NES] CUMMINS; no parallel, no AS, No CA Carb' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='A190484324');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, notes) select gen_random_uuid(), 'A190486513', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Cummins', '[NES] CUMMINS; no parallel, no AS, No CA Carb' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='A190486513');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, notes) select gen_random_uuid(), 'B3G00213', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '[NES] OLD 3.2 -20''; Does Not Parallel w/ Other 500kw Units' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='B3G00213');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'C4G00293', 'big', 500, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C4G00293');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'C4G00294', 'big', 500, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C4G00294');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C5E02263-64', 'big', 1000, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C5E0226364');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C5E02276-77', 'big', 1000, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 40" w/ LG' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C5E0227677');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C5E02286-87', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C5E0228687');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines) select gen_random_uuid(), 'C5E02980-81', 'big', 1000, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C5E0298081');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C5E02982-83', 'big', 1000, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 500}, "B": {"kvaEach": 500}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C5E0298283');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00315/309', 'big', 750, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00315309');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00317/318', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] EMCP 4.4' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00317318');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00574/627', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00574627');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00576/577', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00576577');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00579/581', 'big', 750, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] EMCP 4.4' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00579581');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00580/629', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00580629');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'C9E00582/575', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] Lift Gate' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00582575');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines) select gen_random_uuid(), 'C9E00626/628', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='C9E00626628');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'CBX00416-17', 'big', 750, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='CBX0041617');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines) select gen_random_uuid(), 'CBX00418-19', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='CBX0041819');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at) select gen_random_uuid(), 'GG500104', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now() where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='GG500104');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at) select gen_random_uuid(), 'GG500109', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now() where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='GG500109');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at) select gen_random_uuid(), 'GG500110', 'big', 625, 'down', 'fleet', null, '{}'::jsonb, now(), now() where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='GG500110');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at) select gen_random_uuid(), 'GG500111', 'big', 625, 'down', 'fleet', null, '{}'::jsonb, now(), now() where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='GG500111');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), 'QSL92255/67', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='QSL9225567');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), 'QSL92263/69', 'big', 750, 'down', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='QSL9226369');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, engines, notes) select gen_random_uuid(), 'QSL974188/96', 'big', 750, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '{"A": {"kvaEach": 375}, "B": {"kvaEach": 375}}'::jsonb, '[NES] 20''' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='QSL97418896');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00750', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00750');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00751', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00751');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00752', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00752');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00753', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00753');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'T4A00754-55', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A0075455');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00756', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00756');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00757', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00757');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00758', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00758');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'T4A00759', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='T4A00759');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62502', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] NO load bank on board' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62502');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62503', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] 100kW Loadbank' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62503');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62505', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] NO Loadbank' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62505');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62506', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] NO LOADBANK' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62506');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62508', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] 150 kW Loadbank' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62508');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62509', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] 150 kW Loadbank' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62509');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62510', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] 150 kW Loadbank' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62510');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62511', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] NO Load bank on board' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62511');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62512', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] NO Load bank on board' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62512');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, engines, notes) select gen_random_uuid(), 'TGD62513', 'big', 1250, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Technogen', '{"A": {"kvaEach": 625}, "B": {"kvaEach": 625}}'::jsonb, '[NES] 150 kW Loadbank' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='TGD62513');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12102877', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12102877');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12102987', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12102987');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12102988', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12102988');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12102989', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12102989');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203253', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203253');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203254', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203254');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203255', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203255');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203256', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203256');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203257', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203257');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203258', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203258');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203259', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203259');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203260', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203260');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203261', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203261');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203262', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203262');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203309', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203309');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12203310', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12203310');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204158', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204158');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204159', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204159');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204160', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204160');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204161', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204161');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204162', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204162');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204163', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204163');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204164', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204164');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204165', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204165');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204166', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204166');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204167', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204167');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204168', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204168');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204169', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204169');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204170', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204170');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204171', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204171');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'U12204172', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204172');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, notes) select gen_random_uuid(), 'U12204173', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'HiPower', '[NES] DOES NOT PARALLEL' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U12204173');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), 'U18803Y', 'big', 500, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] SWP; Do Not Parallel; 48'' stepdek skid' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U18803Y');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), 'U21001X', 'big', 500, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] SWP; Do Not Parallel; 48'' stepdek skid' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='U21001X');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'UVC700023', 'big', 700, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Atlas Copco' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='UVC700023');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'UVC700026', 'big', 700, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Atlas Copco' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='UVC700026');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'UVC700301', 'big', 700, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Atlas Copco' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='UVC700301');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'UVC700302', 'big', 700, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'Atlas Copco' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='UVC700302');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), 'X3M00113', 'big', 437.5, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] does not parallel 48'' stepdeck' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X3M00113');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, notes) select gen_random_uuid(), 'X3M00190', 'big', 437.5, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), '[NES] does not parallel 48'' stepdeck' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X3M00190');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00212', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00212');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00216', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00216');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00253', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00253');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00276', 'big', 625, 'down', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00276');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00285', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00285');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00304', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00304');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00309', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00309');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00312', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00312');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00318', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00318');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00320', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00320');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00328', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00328');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00355', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00355');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make, notes) select gen_random_uuid(), 'X5M00374', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT', '[NES] No ping since 12-2020' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00374');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00375', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00375');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00382', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00382');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00384', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00384');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00387', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00387');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00418', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00418');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00443', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00443');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00444', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00444');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00492', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00492');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00494', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00494');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00514', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00514');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00526', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00526');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00528', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00528');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00531', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00531');
insert into units (id, serial, klass, kw, op_status, location_type, location_id, job_meta, created_at, updated_at, make) select gen_random_uuid(), 'X5M00534', 'big', 625, 'staged', 'fleet', null, '{}'::jsonb, now(), now(), 'CAT' where not exists (select 1 from units where upper(regexp_replace(coalesce(serial,''),'[^A-Za-z0-9]','','g'))='X5M00534');

commit;

-- ============================================================
-- VERIFY
-- ============================================================
select count(*) as total_units from units;                              -- expect 212
select count(*) as big_iron from units where klass='big';               -- expect 153
select count(*) as twins from units where engines is not null;          -- expect 50
select count(*) as nes_hard_down from units where op_status='down';     -- expect at least 21
select count(*) as any_style_set from units where engines->>'style' is not null;  -- expect 0
-- no imported unit may carry hours or a service target:
select count(*) as imported_with_hours from units where location_type='fleet' and (current_hours is not null or service_due_hours is not null);  -- expect 0
-- the held-out transposition must NOT have been created:
select serial from units where serial in ('UVC700618','UCV700618');      -- expect UCV700618 only

-- ============================================================
-- POST-RUN VERIFICATION -- one query, one row, run once.
-- Expected values are in the comment beside each column.
-- ============================================================
select
  (select count(*) from units)                                  as total_units,          -- 212
  (select count(*) from units where klass='big')                as big_iron,             -- 153
  (select count(*) from units where klass='small')              as small_iron,           --  59
  (select count(*) from units where engines is not null)        as twins,                --  50
  (select count(*) from units where op_status='down')           as hard_down,            --  21
  (select count(*) from units where location_type='fleet')      as unassigned,           -- 134
  (select count(*) from units
     where location_type='fleet'
       and (current_hours is not null
         or service_due_hours is not null))                     as imported_with_hours,  --   0
  (select count(*) from units where engines->>'style' is not null)
                                                                as style_set,            --   0
  (select count(*) from units where serial='UVC700618')         as transposed_created,   --   0
  (select count(*) from units a join units b
      on a.id <> b.id
     and upper(regexp_replace(coalesce(a.serial,''),'[^A-Za-z0-9]','','g'))
       = upper(regexp_replace(coalesce(b.serial,''),'[^A-Za-z0-9]','','g')))
                                                                as dup_serial_rows;      --   2
-- dup_serial_rows = 2 is the KNOWN D19701 / D19701. pair, counted in both directions.
-- Any number above 2 means the import created a duplicate. It should not be able to.
